name: 'Pipeline'

on:
  push:
    branches: ['main']

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of release (major, minor, patch)'
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch
          - prepatch

jobs:
  continous-integration:
    name: 'Continuous Integration'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm check-format

      - name: Check types
        run: pnpm check-types

      - name: Test
        run: pnpm test

  continious-deployment:
    if: github.event_name == 'workflow_dispatch'

    name: 'Continous Deployment'
    runs-on: ubuntu-latest
    needs: ['continous-integration']

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm release ${{ github.events.inputs.release-type }}
